language: java

install: cd at.fhv.tedapt.releng; mvn clean install -DskipTests=true;

jdk:
  - oraclejdk7

deploy:
  provider: releases
  api_key: 262d9aba83ee09a255cd6107333c9a7dc962eaa1
  local-dir: ./at.fhv.tedapt.releng.p2
  skip_cleanup: true
  on:
    tags: true