language: java

jdk:
  - oraclejdk7

branches:
  only:
    - release
  
script: mvn install -DskipTests=true;
after_success: chmod +x ghs_update.sh; ./ghs_update.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4cc77e533f35ca4547c0
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false