language: java

install: cd at.fhv.tedapt.releng; mvn clean install -DskipTests=true;

jdk:
  - oraclejdk7

deploy:
  provider: releases
  api_key: GitAuth
  local-dir: /home/travis/build/drexedam/Tedapt/at.fhv.tedapt.releng.p2
  skip_cleanup: true
  on:
    tags: true